version: "3"
services:

    redis:
        image: redis
        hostname: redis
        container_name: redis

    web:
        build: .
        #  command: python manage.py runserver 0.0.0.0:8000
        command:  uwsgi --ini uwsgi.ini
        volumes:
        - .:/code
        ports:
        - "8000:8000"
        links:
            - redis:redis  
        restart: always 
    